language: python
matrix:
  include:
    - env: TOXENV=py26
      python: "2.6"
    - env: TOXENV=py27
    - env: TOXENV=py34
    - env: TOXENV=cover
    - env: TOXENV=docs
    - env: TOXENV=flake8
install:
- pip install tox coveralls
script:
- tox
after_success:
- coveralls
